mut_llm:
  model: openai/gpt-5-nano #Â paper uses openai/gpt-3.5-turbo-0301
  api_type: open_ai
  api_base: https://openrouter.ai/api/v1
  api_version: 
  api_key: ${oc.env:OPENROUTER_API_KEY}

xo_llm:
  model: google/gemini-2.5-flash-lite
  api_type: open_ai
  api_base: https://openrouter.ai/api/v1
  api_version: 
  api_key: ${oc.env:OPENROUTER_API_KEY} 