mut_llm:
  model: meta-llama/llama-3.1-8b-instruct #Â paper uses openai/gpt-3.5-turbo-0301
  api_type: open_ai
  api_base: https://openrouter.ai/api/v1
  api_version: 
  api_key: ${oc.env:OPENROUTER_API_KEY}

xo_llm:
  model: meta-llama/llama-3.1-8b-instruct
  api_type: open_ai
  api_base: https://openrouter.ai/api/v1
  api_version: 
  api_key: ${oc.env:OPENROUTER_API_KEY} 