[project]
name = "gatree"
version = "0.2.0"
description = ""
authors = [
{ name = "Tadej Lahovnik", email = "tadej.lahovnik@student.um.si" }
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
"scikit-learn>=1.3.0",
"scipy>=1.11.2",
"numpy>=1.23.0",
"pandas>=1.3.0",
]

[project.optional-dependencies]
docs = [
"sphinx>=5.0",
"sphinx-rtd-theme>=1.0.0",
]

[dependency-groups]
dev = [
"pytest>=7.4.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"